PersonalSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projects.views import *

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls')),
    url(r'^blog/', include('blog.urls')),

]

blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    url(r'^$', views.index, name='index'),
    # ex: /blog/5/
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<project_id>[0-9]+)/details/$', views.detail, name='detail'),
    url(r'^skills/$', views.skills, name='skills'),
]

blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    post_text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    commenter_name = models.CharField(max_length=50, null=True)
    commenter_ip = models.GenericIPAddressField()


class PostTag(models.Model):
    tagged_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    tag_text = models.CharField(max_length=50)

    def __str__(self):
        return self.tag_text

home/models.py
from django.db import models


# Create your models here.

projects/models.py
from django.db import models
from django.utils import timezone
import datetime


class Project(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    date_started = models.DateField()
    date_completed = models.DateField(null=True)
    problems_solved = models.TextField(default="")
    lessons_learned = models.TextField(default="")

    def __str__(self):
        return self.title

    def was_recently_completed(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=180)


class Skill(models.Model):
    name = models.CharField(max_length=50)
    rating = models.FloatField(default=1)

    def __str__(self):
        return self.name


class ProjectSkill(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    reason_used = models.TextField()

    def __str__(self):
        return self.project.__str__() + " required " + self.skill.__str__()

blog/views.py
from django.shortcuts import render


# Create your views here.
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import *
# Create your views here.


def index(request):
    post_list = Post.objects.order_by('-pub_date')
    context = {
        'post_list': post_list
    }
    return render(request, 'blog/index.html', context)


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_list = get_list_or_404(Comment, post=post)
    context = {
        'post': post,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context)

home/views.py
from django.shortcuts import render


# Create your views here.
def contact(request):
    github_username = "wh01683"
    context = {
        'title': "Contact Me",
        'email': 'whowertoniii@gmail.com',
        'mobile_phone': '+1 (478) 390-2179',
        'github_username': github_username,
        'github_link': 'https://github.com/'+github_username,
        'linkedin_username': "Robert Howerton",
        'linkedin_link': "https://www.linkedin.com/in/william-howerton-a7074759?",
    }
    return render(request, 'home/contact.html', context)


def about(request):
    context = {
        'title': 'About Me',
        'p1': "I am a Software Engineer Asc. working for Lockheed Martin in Ashburn, VA. More to come.",
    }
    return render(request, 'home/about.html', context)


def home(request):
    context = {
        'title': "Howerton's Page",
        'p1': "This is a living resume for William Robert Howerton III.",
    }
    return render(request, 'home/home.html', context)

projects/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Project, ProjectSkill, Skill
# Create your views here.


def index(request):
    project_list = Project.objects.order_by('-date_completed')
    context = {
        'project_list': project_list
    }
    return render(request, 'projects/index.html', context)


def detail(request, project_id):
    project_obj = get_object_or_404(Project, pk=project_id)
    project_skill_list = get_list_or_404(ProjectSkill, project=project_obj)
    context = {
        'project': project_obj,
        'project_skill_list': project_skill_list
    }
    return render(request, 'projects/detail.html', context)


def skills(request):
    skill_list = get_list_or_404(Skill)
    context = {
        'skill_list': skill_list,
    }

    return render(request, 'projects/skills.html', context)

templates/blog/detail.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog_style.css' %}"/>
{% block title %}{{ post.title }}{% endblock %}
<h3>Posted on {{ post.pub_date }}</h3>
{% block content %}
    <p>{{ post.post_text }}</p>

    <h2>Comments</h2>
    <ul>
        {% if comment_list %}
            {% for comment in comment_list %}
                <li><div class="commenter">{{ comment.commenter_name }} ({{ comment.commenter_ip }}) said on {{ comment.pub_date }}:</div>
                <br/>
                <div class="comment">{{ comment.comment_text }}</div>
                <br/>
                </li>
            {% endfor %}
        {% else %}
            <p>No comments found for {{ comment.title }}.</p>
        {% endif %}
    </ul>
{% endblock %}

templates/blog/index.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog_style.css' %}"/>
{% block title %}Blog{% endblock %}
{% block content %}
{% if post_list %}
    <ul>
        {% for post in post_list %}
            <li><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}
{% endblock %}

templates/general/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'general/header.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>

<div class="wrapper">
    <div id="header">
        <a href="{% url 'home:home' %}">Home</a>
        <a href="{% url 'home:about' %}">About</a>
        <a href="{% url 'projects:index' %}">Projects</a>
        <a href="{% url 'projects:skills' %}">Skills</a>
        <a href="{% url 'blog:index' %}">Blog</a>
        <a href="{% url 'home:contact' %}">Contact</a>
    </div>
    <div id="page_container">
        <div id="sidebar">Testing testing testing testing testing2 testing 2</div>
        <div id="content">
        <h1>{% block title %} {% endblock %}</h1>
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

</html>

templates/home/about.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>

{% block title %} {{ title }} {% endblock %}
{% block content %}
<p>{{ p1 }}</p>
<p>You may find my contact information <a href="{% url 'home:contact'%}">here</a>.</p>
{% endblock %}

templates/home/contact.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
{% block title %}{{ title }}{% endblock %}
{% block content %}
<p>e-mail: <a href="mailto:{{ email }}">{{ email }}</a></p>
<p>mobile: {{ mobile_phone }}</p>
<p>github: <a href="{{ github_link }}">{{ github_username}} </a></p>
<p>linkedin: <a href="{{ linkedin_link }}">{{ linkedin_username}} </a></p>
{% endblock %}

templates/home/home.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <p>{{ p1 }}</p>
{% endblock %}

templates/projects/detail.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
{% block title %}{{ project.title }}{% endblock %}

{% block content %}
    <p>{{ project.description }}</p>
    <h2>Problems Solved</h2>
    <p>{{ project.problems_solved }}</p>
    <h2>Lessons Learned</h2>
    <p>{{ project.lessons_learned }}</p>

    <h2> Skills Used </h2>
    <ul>
        {% if project_skill_list %}
            {% for project_skill in project_skill_list %}
                <li><h3>{{ project_skill.skill.name }}</h3>{{ project_skill.reason_used }}</li>
            {% endfor %}
        {% else %}
            <p>No skills found for {{ project.title }}.</p>
        {% endif %}
    </ul>
{% endblock %}

templates/projects/index.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
{% block title %}Projects{% endblock %}
{% block content %}
{% if project_list %}
    <ul>
        {% for project in project_list %}
            <li><a href="{% url 'projects:detail' project.id %}">{{ project.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No projects are available.</p>
{% endif %}
{% endblock %}

templates/projects/skills.html
{% extends 'general/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'general/general.css' %}"/>
{% block title %}Skills{% endblock %}
{% block content %}
{% if skill_list %}
    <ul>
        {% for skill in skill_list %}
            <li>{{ skill.name }} <span class="stars" title="{{ skill.rating }}">
                <span style="width: calc({{ skill.rating }}/5*100%)"/>
            </span></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No skills are available.</p>
{% endif %}
{% endblock %}